 #!/bin/bash

# Filename for the report
REPORT_FILE="system_report.txt"
NAME="OKAFOR GOODNESS"

# Slack webhook URL


# Create or clear the report file
echo "Generating system report..." > "$REPORT_FILE"
echo "===========================" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Memory Usage
echo "Memory Usage:" >> "$REPORT_FILE"
free -h >> "$REPORT_FILE"

# Disk Usage
echo "Disk Usage:" >> "$REPORT_FILE"
df -h >> "$REPORT_FILE"

# CPU Information
echo "CPU Info: $(lscpu | grep 'Model name' | awk -F ':' '{ print $2 }' | xargs)" >> "$REPORT_FILE"

# Finish report
echo "" >> "$REPORT_FILE"
echo "Report generated on: $(date)" >> "$REPORT_FILE"

# Print report file location
echo "System report saved to: $REPORT_FILE"

# Read the report file content
REPORT_CONTENT=$(<"$REPORT_FILE")

# Send the report content to Slack
MESSAGE="System report generated by $NAME on $(date).\n\n\`\`\`$REPORT_CONTENT\`\`\`"
response=$(curl -s -X POST -H 'Content-type: application/json' --data "{\"text\":\"${MESSAGE}\"}" $SLACK_WEBHOOK_URL)

if [[ $response == *"ok"* ]]; then
    echo "Report sent to Slack successfully!"
else
    echo "Failed to send report to Slack: $response"
fi
